# Generated by Django 5.2.4 on 2025-07-25 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(null=True, upload_to='cardapio/')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=255)),
                ('cliente_endereco', models.CharField(max_length=255)),
                ('cliente_telefone', models.CharField(max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_preparo', 'Em Preparo'), ('a_caminho', 'A Caminho'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.itemcardapio')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='dashboard.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('imagem', models.ImageField(null=True, upload_to='restaurante/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='dashboard.restaurante'),
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardapio', to='dashboard.restaurante'),
        ),
    ]
