# Generated by Django 5.2.4 on 2025-07-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='itemcardapio',
            name='imagem_url',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='imagem',
            field=models.ImageField(null=True, upload_to='cardapio/'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='imagem',
            field=models.ImageField(null=True, upload_to='restaurante/'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='senha',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
